INSERT INTO tb_course (name, description, hours, amount_class, year) VALUES ('HTML5', 'Curso de HTML5', 40, 37, 2014);
INSERT INTO tb_course (name, description, hours, amount_class, year) VALUES ('Algoritmos', 'Lógica de Programação', 20, 15, 2014);
INSERT INTO tb_course (name, description, hours, amount_class, year) VALUES ('Photoshop', 'Dicas de Photoshop CC', 10, 8, 2014);
INSERT INTO tb_course (name, description, hours, amount_class, year) VALUES ('Word', 'Curso completo de Word', 40, 30, 2016);
INSERT INTO tb_course (name, description, hours, amount_class, year) VALUES ('POO', 'Curso de Programação Orientada a Objetos', 60, 35, 2016);
INSERT INTO tb_course (name, description, hours, amount_class, year) VALUES ('C++', 'Curso de C++ com Orientação a Objetos', 40, 25, 2017);
INSERT INTO tb_course (name, description, hours, amount_class, year) VALUES ('Android', 'Curso de Desenvolvimento de Aplicativos para Android', 60, 30, 2018);
INSERT INTO tb_course (name, description, hours, amount_class, year) VALUES ('JavaScript', 'Curso de JavaScript', 35, 18, 2017);
INSERT INTO tb_course (name, description, hours, amount_class, year) VALUES ('Swift', 'Curso de Desenvolvimento de Aplicativos para iOS', 60, 30, 2019);
INSERT INTO tb_course (name, description, hours, amount_class, year) VALUES ('Premiere', 'Curso de Edição de Vídeos com Premiere', 40, 15, 2016);
INSERT INTO tb_course (name, description, hours, amount_class, year) VALUES ('After Effects', 'Curso de Efeitos em Vídeos com After Effects', 30, 20, 2017);
INSERT INTO tb_course (name, description, hours, amount_class, year) VALUES ('WordPress', 'Curso de Criação de Sites com WordPress', 60, 30, 2019);
INSERT INTO tb_course (name, description, hours, amount_class, year) VALUES ('Modelagem de Dados', 'Curso de Modelagem de Dados', 30, 12, 2020);